# JWT Authentication Application - Docker Compose Configuration
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: jwt-auth-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jwtauthdb
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d # execute scripts in mongo-init file on first run of docker-compose up
    networks:
      - jwt-auth-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Spring Boot
  # sedo-jwt-auth-app:
  #   build: .
  #   container_name: sedo-jwt-auth-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATA_MONGODB_HOST: mongodb
  #     SPRING_DATA_MONGODB_PORT: 27017
  #     SPRING_DATA_MONGODB_DATABASE: jwtauthdb
  #     SPRING_DATA_MONGODB_USERNAME: admin
  #     SPRING_DATA_MONGODB_PASSWORD: password123
  #     SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #   networks:
  #     - jwt-auth-network

volumes:
  mongodb_data:
    driver: local

networks:
  jwt-auth-network:
    driver: bridge
