# Docker Compose file with image to upload in dockerhub
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sedo-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jwtauthdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - sedo-network

  minio:
    image: minio/minio:latest
    container_name: sedo-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - sedo-network

  sedo-backend-app:
    image: yayabbln/store_management:sedo-store-app-v1.0.0 #image name from private dockerhub
    container_name: sedo-backend-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: jwtauthdb
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password123
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      APP_MINIO_URL: http://minio:9000
      APP_MINIO_ACCESS_KEY: minioadmin
      APP_MINIO_SECRET_KEY: minioadmin123
      APP_MINIO_BUCKET_NAME: product-images
      APP_BACKEND_URL: http://localhost:8080
      APP_FRONTEND_URL: http://localhost:4000
      APP_EMAIL_FROM: sedosebe.store@gmail.com
    depends_on:
      - mongodb
      - minio
    networks:
      - sedo-network

  angular-frontend:
    image: yayabbln/store_management:ui-sedo-v1.0.0 #image name from private dockerhub
    container_name: sedo-frontend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - sedo-backend-app
    networks:
      - sedo-network

volumes:
  mongodb_data:
  minio_data:

networks:
  sedo-network:
    driver: bridge