server:
  port: 8080

spring:
  application:
    name: sedo-jwt-auth-app
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jwtauthdb
      username: admin
      password: password123
      authentication-database: admin

# JWT configuration
jwt:
  secret: myDefaultSecretKeyForJwtTokenGeneration1234567890
  expiration: 86400000 # 24h in ms
