server:
  port: 8080

spring:
  application:
    name: sedo-store-management-system
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:jwtauthdb}
      username: ${SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:password123}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
  cache:
    type: simple
  mail:
    host: smtp.gmail.com
    port: 587
    username: sedosebe.store@gmail.com
    password: lhae rrkb qrmf zwgk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Application configuration
app:
  mail:
    from: ${APP_EMAIL_FROM:sedosebe.store@gmail.com}
  backend:
    url: ${APP_BACKEND_URL:http://localhost:8080}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:4200}
  minio:
    url: ${APP_MINIO_URL:http://localhost:9000}
    access-key: ${APP_MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${APP_MINIO_SECRET_KEY:minioadmin123}
    bucket-name: ${APP_MINIO_BUCKET_NAME:product-images}
