server:
  port: 8080

spring:
  application:
    name: sedo-store-management-system
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jwtauthdb
      username: admin
      password: password123
      authentication-database: admin
  cache:
    type: simple

# JWT configuration
#jwt:
#  secret: myDefaultSecretKeyForJwtTokenGeneration1234567890
#  access-token-expiration: 1_000
#  refresh-token-expiration: 2_000

# Application configuration
app:
  store:
    name: "Magasin SEDO"
    tax-rate: 0.20 # 20% TVA France
    currency: "EUR"
    timezone: "Europe/Paris"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
